server:
  port: 8888

spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/demo?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Taipei&&characterEncoding=utf-8
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456

mybatis:
#  ???????????mapper???????????
#  mapper-locations: com/leetasktw/mapper/*.xml
  type-aliases-package: com.leetasktw.pojo
